/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Track as PrismaTrack,
  PlaylistTrack as PrismaPlaylistTrack,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class TrackServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.TrackCountArgs, "select">): Promise<number> {
    return this.prisma.track.count(args);
  }

  async tracks(args: Prisma.TrackFindManyArgs): Promise<PrismaTrack[]> {
    return this.prisma.track.findMany(args);
  }
  async track(args: Prisma.TrackFindUniqueArgs): Promise<PrismaTrack | null> {
    return this.prisma.track.findUnique(args);
  }
  async createTrack(args: Prisma.TrackCreateArgs): Promise<PrismaTrack> {
    return this.prisma.track.create(args);
  }
  async updateTrack(args: Prisma.TrackUpdateArgs): Promise<PrismaTrack> {
    return this.prisma.track.update(args);
  }
  async deleteTrack(args: Prisma.TrackDeleteArgs): Promise<PrismaTrack> {
    return this.prisma.track.delete(args);
  }

  async uploadFile<T extends Prisma.TrackFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrackFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaTrack> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "file";
    const file = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.track.update({
      where: args.where,

      data: {
        file: file as InputJsonValue,
      },
    });
  }

  async downloadFile<T extends Prisma.TrackFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrackFindUniqueArgs>
  ): Promise<FileDownload> {
    const { file } = await this.prisma.track.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      file as unknown as LocalStorageFile
    );
  }

  async deleteFile<T extends Prisma.TrackFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrackFindUniqueArgs>
  ): Promise<PrismaTrack> {
    const { file } = await this.prisma.track.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      file as unknown as LocalStorageFile
    );

    return await this.prisma.track.update({
      where: args.where,

      data: {
        file: Prisma.DbNull,
      },
    });
  }

  async findPlaylistTracks(
    parentId: string,
    args: Prisma.PlaylistTrackFindManyArgs
  ): Promise<PrismaPlaylistTrack[]> {
    return this.prisma.track
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .playlistTracks(args);
  }
}
